# named list of all robots
robots:
  cf1:
    enabled: true
    uri: udp://0.0.0.0:19850
    initial_position: [0.5, 0.0, 0.0]
    type: cf_sim  # see robot_types

  cf2:
    enabled: true
    uri: udp://0.0.0.0:19851
    initial_position: [-0.25, 0.433, 0.0]
    type: cf_sim  # see robot_types

  cf3:
    enabled: true
    uri: udp://0.0.0.0:19852
    initial_position: [-0.25, -0.433, 0.0]
    type: cf_sim  # see robot_types

# Definition of the various robot types
robot_types:
  cf_sim:
    motion_capture:
      enabled: false
    big_quad: false
    firmware_logging:
      enabled: true
  cf:
    motion_capture:
      enabled: false
    big_quad: false
    battery:
      voltage_warning: 3.8  # V
      voltage_critical: 3.7 # V
    # firmware_params:
    #   kalman:
    #     pNAcc_xy: 1.0 # default 0.5
    firmware_logging:
      enabled: true
      custom_topics:
        poseKalman:
          frequency: 10
          vars: ["kalman.statePX", "kalman.statePY", "kalman.statePZ"]
        twistKalman:
          frequency: 10
          vars: ["kalman.stateVX", "kalman.stateVY", "kalman.stateVZ"]
        accKalman:
          frequency: 10
          vars: ["kalman.stateAX", "kalman.stateAY", "kalman.stateAZ"]
        acceleration: 
          frequency: 10
          vars: ["acc.x", "acc.y", "acc.z"]
        thrust:
          frequency: 50
          vars: ["motor.m1", "motor.m2", "motor.m3", "motor.m4"]
        stabilizer:
          frequency: 10 # Hz
          vars: ["stabilizer.roll", "stabilizer.pitch", "stabilizer.yaw"]

  cf_mocap_deck:
    motion_capture:
      enabled: true
      # only if enabled; see motion_capture.yaml
      marker: mocap_deck
      dynamics: default
    big_quad: false
    battery:
      voltage_warning: 3.8  # V
      voltage_critical: 3.7 # V

    # firmware_params:
    #   kalman:
    #     pNAcc_xy: 1.0 # default 0.5

# global settings for all robots
all:
  firmware_logging:
    enabled: true
    default_topics:
      pose:
        frequency: 100 # Hz
      odom:
        frequency: 100 # Hz
  firmware_params:
    commander:
      enHighLevel: 1
    stabilizer:
      estimator: 2 # 1: complementary, 2: kalman
      controller: 1 # 1: PID, 2: mellinger
    # pid_attitude:
    #   roll_kp: 10
    #   roll_ki: 0
    #   roll_kd: 0
    #   pitch_kp: 10
    #   pitch_ki: 0
    #   pitch_kd: 0
    # pid_rate:
    #   roll_kp: 500
    #   roll_ki: 500
    #   roll_kd: 3.6
    #   pitch_kp: 500
    #   pitch_ki: 500
    #   pitch_kd: 3.6
    #   rateFiltEn: 1
    # ring:
    #   effect: 16 # 6: double spinner, 7: solid color, 16: packetRate
    #   solidBlue: 255 # if set to solid color
    #   solidGreen: 0 # if set to solid color
    #   solidRed: 0 # if set to solid color
    #   headlightEnable: 0
    locSrv:
      extPosStdDev: 1e-3
      extQuatStdDev: 0.5e-1
    # kalman:
    #   resetEstimation: 1
  broadcasts:
    num_repeats: 15 # number of times broadcast commands are repeated
    delay_between_repeats_ms: 1 # delay in milliseconds between individual repeats