calibs:
  0:
    sweeps:
    - curve: 0.2440185546875
      gibmag: -0.0028629302978515625
      gibphase: 1.619140625
      ogeemag: -0.126220703125
      ogeephase: 0.7451171875
      phase: 0.0
      tilt: -0.044830322265625
    - curve: 0.372802734375
      gibmag: -0.0030231475830078125
      gibphase: 1.7822265625
      ogeemag: -0.114501953125
      ogeephase: 0.85546875
      phase: -0.006389617919921875
      tilt: 0.045501708984375
    uid: 2976668033
  1:
    sweeps:
    - curve: -0.0762939453125
      gibmag: 0.00634765625
      gibphase: 1.03125
      ogeemag: -0.60498046875
      ogeephase: 1.2421875
      phase: 0.0
      tilt: -0.045135498046875
    - curve: 0.32080078125
      gibmag: 0.006092071533203125
      gibphase: 2.349609375
      ogeemag: -0.5859375
      ogeephase: 2.046875
      phase: -0.002712249755859375
      tilt: 0.044097900390625
    uid: 1982009799
geos:
  0:
    origin:
    - -0.22686205804347992
    - 0.9304068684577942
    - 1.9992340803146362
    rotation:
    - - 0.054207608103752136
      - -0.9983091354370117
      - -0.020985377952456474
    - - -0.6979864239692688
      - -0.05291242152452469
      - 0.714153528213501
    - - -0.7140563726425171
      - -0.02406504563987255
      - -0.6996744871139526
  1:
    origin:
    - 0.9218653440475464
    - 0.9647921323776245
    - 2.023404836654663
    rotation:
    - - 0.03845009207725525
      - -0.9990336298942566
      - -0.021292509511113167
    - - -0.6886804103851318
      - -0.04193296283483505
      - 0.7238514423370361
    - - -0.7240447998046875
      - -0.013168418779969215
      - -0.6896272301673889
systemType: 2
type: lighthouse_system_configuration
version: '1'
