# named list of all robots
robots:
  cf1:
    enabled: true
    uri: udp://0.0.0.0:19850
    initial_position: [0.2, 0.0, 0.0]
    type: cf_sim  # see robot_types

  cf2:
    enabled: true
    uri: udp://0.0.0.0:19851
    initial_position: [0.0, 0.2, 0.0]
    type: cf_sim  # see robot_types

  cf3:
    enabled: true
    uri: udp://0.0.0.0:19852
    initial_position: [0.0, -0.2, 0.0]
    type: cf_sim  # see robot_types

# Definition of the various robot types
robot_types:
  cf_sim:
    motion_capture:
      enabled: false
    big_quad: false
    firmware_logging:
      enabled: true

# global settings for all robots
all:
  firmware_logging:
    enabled: true
    default_topics:
      pose:
        frequency: 100 # Hz
      odom:
        frequency: 100 # Hz
  firmware_params:
    commander:
      enHighLevel: 1
    stabilizer:
      estimator: 2 # 1: complementary, 2: kalman
      controller: 2 # 1: PID, 2: mellinger
    locSrv:
      extPosStdDev: 1e-3
      extQuatStdDev: 0.5e-1
    # kalman:
    #   resetEstimation: 1
  broadcasts:
    num_repeats: 15 # number of times broadcast commands are repeated
    delay_between_repeats_ms: 1 # delay in milliseconds between individual repeats