# named list of all robots
robots:
  cf1:
    enabled: true
    uri: radio://0/80/2M/E7E7E7E7E1
    initial_position: [0.0, 0.0, 0.0]
    type: cf  # see robot_types
    # firmware_params:
    #   kalman:
    #     pNAcc_xy: 1.0 # default 0.5


# Definition of the various robot types
robot_types:
  cf_sim:
    motion_capture:
      enabled: false
    big_quad: false
    # battery:
    #   voltage_warning: 3.8  # V
    #   voltage_critical: 3.7 # V
    # firmware_logging:

  cf:
    motion_capture:
      enabled: false
    big_quad: false
    battery:
      voltage_warning: 3.8  # V
      voltage_critical: 3.7 # V
    # firmware_params:
    #   kalman:
    #     pNAcc_xy: 1.0 # default 0.5
    firmware_logging:
      enabled: true
      default_topics:
        pose:
          frequency: 100
      custom_topics:
        velocity:
          frequency: 100
          vars: ["kalman.statePX", "kalman.statePY", "kalman.statePZ"]
        stabilizer:
          frequency: 1 # Hz
          vars: ["stabilizer.roll", "stabilizer.pitch", "stabilizer.yaw"]
        acceleration: 
          frequency: 1
          vars: ["acc.x", "acc.y", "acc.z"]
        thrust:
          frequency: 50
          vars: ["motor.m1", "motor.m2", "motor.m3", "motor.m4"]

# global settings for all robots
all:
  # firmware logging for all drones (use robot_types/type_name to set per type, or
  # robots/drone_name to set per drone)
  firmware_logging:
    enabled: true
    default_topics:
     # remove to disable default topic
      pose:
        frequency: 10 # Hz
      odom:
        frequency: 100 # Hz
    # custom_topics:
  # firmware parameters for all drones (use robot_types/type_name to set per type, or
  # robots/drone_name to set per drone)
  firmware_params:
    commander:
      enHighLevel: 1
    stabilizer:
      estimator: 2 # 1: complementary, 2: kalman
      controller: 1 # 1: PID, 2: mellinger
    locSrv:
      extPosStdDev: 1e-3
      extQuatStdDev: 0.5e-1
    # kalman:
    #   resetEstimation: 1
  broadcasts:
    num_repeats: 15 # number of times broadcast commands are repeated
    delay_between_repeats_ms: 1 # delay in milliseconds between individual repeats